package com.prueba.model.wshistory;

import java.io.Serializable;
import java.util.Date;

import com.prueba.model.EntityBase;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import com.prueba.constraints.XSS;
import com.prueba.gui.importer.ConstraintImportField;
import com.prueba.gui.importer.ConstraintImportTable;

@XmlRootElement
@ConstraintImportTable(keys={"id"})
public class WsHistory extends EntityBase implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ws_history.id
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
	@NotNull
	@ConstraintImportField(columnName="id",messageError="error.wshistory.id",pattern="^(\\-)?\\d+(\\.\\d+)?$",isPK=true,isCompulsory=true)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ws_history.userId
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
	@NotNull
	@ConstraintImportField(columnName="userid",messageError="error.wshistory.userid",pattern="^(\\-)?\\d+(\\.\\d+)?$",isPK=false,isCompulsory=false)
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ws_history.userName
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
	@XSS
	@NotNull
	@Size(min=0,max=100)
	@ConstraintImportField(columnName="username",messageError="error.wshistory.username",pattern=".+",isPK=false,isCompulsory=false)
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ws_history.ip
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
	@XSS
	@NotNull
	@Size(min=0,max=100)
	@ConstraintImportField(columnName="ip",messageError="error.wshistory.ip",pattern=".+",isPK=false,isCompulsory=false)
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ws_history.serviceRequestDate
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
	@NotNull
	@ConstraintImportField(columnName="servicerequestdate",messageError="error.wshistory.servicerequestdate",pattern="^^(0[1-9]|[12][0-9]|3[01])[- /.](0[1-9]|1[012])[- /.](19|20)\\d\\d$",isPK=false,isCompulsory=false)
    private Date servicerequestdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ws_history.service
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
	@XSS
	@NotNull
	@Size(min=0,max=255)
	@ConstraintImportField(columnName="service",messageError="error.wshistory.service",pattern=".+",isPK=false,isCompulsory=false)
    private String service;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ws_history.responseFormat
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
	@XSS
	@NotNull
	@Size(min=0,max=255)
	@ConstraintImportField(columnName="responseformat",messageError="error.wshistory.responseformat",pattern=".+",isPK=false,isCompulsory=false)
    private String responseformat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ws_history.serviceName
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
	@XSS
	@NotNull
	@Size(min=0,max=70)
	@ConstraintImportField(columnName="servicename",messageError="error.wshistory.servicename",pattern=".+",isPK=false,isCompulsory=false)
    private String servicename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ws_history.numberOfElements
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
	@NotNull
	@ConstraintImportField(columnName="numberofelements",messageError="error.wshistory.numberofelements",pattern="^(\\-)?\\d+(\\.\\d+)?$",isPK=false,isCompulsory=false)
    private Integer numberofelements;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ws_history
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ws_history.id
     *
     * @return the value of t_ws_history.id
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ws_history.id
     *
     * @param id the value for t_ws_history.id
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ws_history.userId
     *
     * @return the value of t_ws_history.userId
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ws_history.userId
     *
     * @param userid the value for t_ws_history.userId
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ws_history.userName
     *
     * @return the value of t_ws_history.userName
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ws_history.userName
     *
     * @param username the value for t_ws_history.userName
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ws_history.ip
     *
     * @return the value of t_ws_history.ip
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ws_history.ip
     *
     * @param ip the value for t_ws_history.ip
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ws_history.serviceRequestDate
     *
     * @return the value of t_ws_history.serviceRequestDate
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public Date getServicerequestdate() {
        return servicerequestdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ws_history.serviceRequestDate
     *
     * @param servicerequestdate the value for t_ws_history.serviceRequestDate
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public void setServicerequestdate(Date servicerequestdate) {
        this.servicerequestdate = servicerequestdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ws_history.service
     *
     * @return the value of t_ws_history.service
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public String getService() {
        return service;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ws_history.service
     *
     * @param service the value for t_ws_history.service
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public void setService(String service) {
        this.service = service == null ? null : service.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ws_history.responseFormat
     *
     * @return the value of t_ws_history.responseFormat
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public String getResponseformat() {
        return responseformat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ws_history.responseFormat
     *
     * @param responseformat the value for t_ws_history.responseFormat
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public void setResponseformat(String responseformat) {
        this.responseformat = responseformat == null ? null : responseformat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ws_history.serviceName
     *
     * @return the value of t_ws_history.serviceName
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public String getServicename() {
        return servicename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ws_history.serviceName
     *
     * @param servicename the value for t_ws_history.serviceName
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public void setServicename(String servicename) {
        this.servicename = servicename == null ? null : servicename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ws_history.numberOfElements
     *
     * @return the value of t_ws_history.numberOfElements
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public Integer getNumberofelements() {
        return numberofelements;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ws_history.numberOfElements
     *
     * @param numberofelements the value for t_ws_history.numberOfElements
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public void setNumberofelements(Integer numberofelements) {
        this.numberofelements = numberofelements;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ws_history
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WsHistory other = (WsHistory) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getIp() == null ? other.getIp() == null : this.getIp().equals(other.getIp()))
            && (this.getServicerequestdate() == null ? other.getServicerequestdate() == null : this.getServicerequestdate().equals(other.getServicerequestdate()))
            && (this.getService() == null ? other.getService() == null : this.getService().equals(other.getService()))
            && (this.getResponseformat() == null ? other.getResponseformat() == null : this.getResponseformat().equals(other.getResponseformat()))
            && (this.getServicename() == null ? other.getServicename() == null : this.getServicename().equals(other.getServicename()))
            && (this.getNumberofelements() == null ? other.getNumberofelements() == null : this.getNumberofelements().equals(other.getNumberofelements()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ws_history
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getIp() == null) ? 0 : getIp().hashCode());
        result = prime * result + ((getServicerequestdate() == null) ? 0 : getServicerequestdate().hashCode());
        result = prime * result + ((getService() == null) ? 0 : getService().hashCode());
        result = prime * result + ((getResponseformat() == null) ? 0 : getResponseformat().hashCode());
        result = prime * result + ((getServicename() == null) ? 0 : getServicename().hashCode());
        result = prime * result + ((getNumberofelements() == null) ? 0 : getNumberofelements().hashCode());
        return result;
    }
}
