package com.prueba.persistence.grouppermission;

import com.prueba.model.grouppermission.GroupPermission;
import com.prueba.model.grouppermission.GroupPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.prueba.persistence.PersistenceBase;
public interface GroupPermissionMapper extends PersistenceBase<GroupPermission, GroupPermissionExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int countByExample(GroupPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int deleteByExample(GroupPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int insert(GroupPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int insertSelective(GroupPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    List<GroupPermission> selectByExample(GroupPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    GroupPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int updateByExampleSelective(@Param("record") GroupPermission record, @Param("example") GroupPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int updateByExample(@Param("record") GroupPermission record, @Param("example") GroupPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int updateByPrimaryKeySelective(GroupPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int updateByPrimaryKey(GroupPermission record);
}
