package com.prueba.model.usergroup;

import java.util.ArrayList;
import java.util.List;

import com.prueba.model.ExampleBase;
import com.prueba.model.CriteriaBase;
public class UserGroupExample extends ExampleBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public UserGroupExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdUserIsNull() {
            addCriterion("id_user is null");
            return (Criteria) this;
        }

        public Criteria andIdUserIsNotNull() {
            addCriterion("id_user is not null");
            return (Criteria) this;
        }

        public Criteria andIdUserEqualTo(Integer value) {
            addCriterion("id_user =", value, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserNotEqualTo(Integer value) {
            addCriterion("id_user <>", value, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserGreaterThan(Integer value) {
            addCriterion("id_user >", value, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_user >=", value, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserLessThan(Integer value) {
            addCriterion("id_user <", value, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserLessThanOrEqualTo(Integer value) {
            addCriterion("id_user <=", value, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserIn(List<Integer> values) {
            addCriterion("id_user in", values, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserNotIn(List<Integer> values) {
            addCriterion("id_user not in", values, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserBetween(Integer value1, Integer value2) {
            addCriterion("id_user between", value1, value2, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserNotBetween(Integer value1, Integer value2) {
            addCriterion("id_user not between", value1, value2, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdGroupIsNull() {
            addCriterion("id_group is null");
            return (Criteria) this;
        }

        public Criteria andIdGroupIsNotNull() {
            addCriterion("id_group is not null");
            return (Criteria) this;
        }

        public Criteria andIdGroupEqualTo(Integer value) {
            addCriterion("id_group =", value, "idGroup");
            return (Criteria) this;
        }

        public Criteria andIdGroupNotEqualTo(Integer value) {
            addCriterion("id_group <>", value, "idGroup");
            return (Criteria) this;
        }

        public Criteria andIdGroupGreaterThan(Integer value) {
            addCriterion("id_group >", value, "idGroup");
            return (Criteria) this;
        }

        public Criteria andIdGroupGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_group >=", value, "idGroup");
            return (Criteria) this;
        }

        public Criteria andIdGroupLessThan(Integer value) {
            addCriterion("id_group <", value, "idGroup");
            return (Criteria) this;
        }

        public Criteria andIdGroupLessThanOrEqualTo(Integer value) {
            addCriterion("id_group <=", value, "idGroup");
            return (Criteria) this;
        }

        public Criteria andIdGroupIn(List<Integer> values) {
            addCriterion("id_group in", values, "idGroup");
            return (Criteria) this;
        }

        public Criteria andIdGroupNotIn(List<Integer> values) {
            addCriterion("id_group not in", values, "idGroup");
            return (Criteria) this;
        }

        public Criteria andIdGroupBetween(Integer value1, Integer value2) {
            addCriterion("id_group between", value1, value2, "idGroup");
            return (Criteria) this;
        }

        public Criteria andIdGroupNotBetween(Integer value1, Integer value2) {
            addCriterion("id_group not between", value1, value2, "idGroup");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_group
     *
     * @mbggenerated do_not_delete_during_merge Tue Oct 08 08:20:18 CEST 2013
     */
public static class Criteria extends GeneratedCriteria implements CriteriaBase{

	 	public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return this;
        }
    	 	public Criteria andIdGroupLike(String value) {
            addCriterion("id_group like", value, "idGroup");
            return this;
        }
    	 	public Criteria andIdUserLike(String value) {
            addCriterion("id_user like", value, "idUser");
            return this;
        }
    

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
