package com.prueba.model.vgrouppermission;

import java.util.ArrayList;
import java.util.List;

import com.prueba.model.ExampleBase;
import com.prueba.model.CriteriaBase;
public class VGroupPermissionExample extends ExampleBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_group_permission
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_group_permission
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_group_permission
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_group_permission
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public VGroupPermissionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_group_permission
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_group_permission
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_group_permission
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_group_permission
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_group_permission
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_group_permission
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_group_permission
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_group_permission
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_group_permission
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_group_permission
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table v_group_permission
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdGroupIsNull() {
            addCriterion("id_group is null");
            return (Criteria) this;
        }

        public Criteria andIdGroupIsNotNull() {
            addCriterion("id_group is not null");
            return (Criteria) this;
        }

        public Criteria andIdGroupEqualTo(Integer value) {
            addCriterion("id_group =", value, "idGroup");
            return (Criteria) this;
        }

        public Criteria andIdGroupNotEqualTo(Integer value) {
            addCriterion("id_group <>", value, "idGroup");
            return (Criteria) this;
        }

        public Criteria andIdGroupGreaterThan(Integer value) {
            addCriterion("id_group >", value, "idGroup");
            return (Criteria) this;
        }

        public Criteria andIdGroupGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_group >=", value, "idGroup");
            return (Criteria) this;
        }

        public Criteria andIdGroupLessThan(Integer value) {
            addCriterion("id_group <", value, "idGroup");
            return (Criteria) this;
        }

        public Criteria andIdGroupLessThanOrEqualTo(Integer value) {
            addCriterion("id_group <=", value, "idGroup");
            return (Criteria) this;
        }

        public Criteria andIdGroupIn(List<Integer> values) {
            addCriterion("id_group in", values, "idGroup");
            return (Criteria) this;
        }

        public Criteria andIdGroupNotIn(List<Integer> values) {
            addCriterion("id_group not in", values, "idGroup");
            return (Criteria) this;
        }

        public Criteria andIdGroupBetween(Integer value1, Integer value2) {
            addCriterion("id_group between", value1, value2, "idGroup");
            return (Criteria) this;
        }

        public Criteria andIdGroupNotBetween(Integer value1, Integer value2) {
            addCriterion("id_group not between", value1, value2, "idGroup");
            return (Criteria) this;
        }

        public Criteria andNameGroupIsNull() {
            addCriterion("name_group is null");
            return (Criteria) this;
        }

        public Criteria andNameGroupIsNotNull() {
            addCriterion("name_group is not null");
            return (Criteria) this;
        }

        public Criteria andNameGroupEqualTo(String value) {
            addCriterion("name_group =", value, "nameGroup");
            return (Criteria) this;
        }

        public Criteria andNameGroupNotEqualTo(String value) {
            addCriterion("name_group <>", value, "nameGroup");
            return (Criteria) this;
        }

        public Criteria andNameGroupGreaterThan(String value) {
            addCriterion("name_group >", value, "nameGroup");
            return (Criteria) this;
        }

        public Criteria andNameGroupGreaterThanOrEqualTo(String value) {
            addCriterion("name_group >=", value, "nameGroup");
            return (Criteria) this;
        }

        public Criteria andNameGroupLessThan(String value) {
            addCriterion("name_group <", value, "nameGroup");
            return (Criteria) this;
        }

        public Criteria andNameGroupLessThanOrEqualTo(String value) {
            addCriterion("name_group <=", value, "nameGroup");
            return (Criteria) this;
        }

        public Criteria andNameGroupLike(String value) {
            addCriterion("name_group like", value, "nameGroup");
            return (Criteria) this;
        }

        public Criteria andNameGroupNotLike(String value) {
            addCriterion("name_group not like", value, "nameGroup");
            return (Criteria) this;
        }

        public Criteria andNameGroupIn(List<String> values) {
            addCriterion("name_group in", values, "nameGroup");
            return (Criteria) this;
        }

        public Criteria andNameGroupNotIn(List<String> values) {
            addCriterion("name_group not in", values, "nameGroup");
            return (Criteria) this;
        }

        public Criteria andNameGroupBetween(String value1, String value2) {
            addCriterion("name_group between", value1, value2, "nameGroup");
            return (Criteria) this;
        }

        public Criteria andNameGroupNotBetween(String value1, String value2) {
            addCriterion("name_group not between", value1, value2, "nameGroup");
            return (Criteria) this;
        }

        public Criteria andIdPermissionIsNull() {
            addCriterion("id_permission is null");
            return (Criteria) this;
        }

        public Criteria andIdPermissionIsNotNull() {
            addCriterion("id_permission is not null");
            return (Criteria) this;
        }

        public Criteria andIdPermissionEqualTo(Integer value) {
            addCriterion("id_permission =", value, "idPermission");
            return (Criteria) this;
        }

        public Criteria andIdPermissionNotEqualTo(Integer value) {
            addCriterion("id_permission <>", value, "idPermission");
            return (Criteria) this;
        }

        public Criteria andIdPermissionGreaterThan(Integer value) {
            addCriterion("id_permission >", value, "idPermission");
            return (Criteria) this;
        }

        public Criteria andIdPermissionGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_permission >=", value, "idPermission");
            return (Criteria) this;
        }

        public Criteria andIdPermissionLessThan(Integer value) {
            addCriterion("id_permission <", value, "idPermission");
            return (Criteria) this;
        }

        public Criteria andIdPermissionLessThanOrEqualTo(Integer value) {
            addCriterion("id_permission <=", value, "idPermission");
            return (Criteria) this;
        }

        public Criteria andIdPermissionIn(List<Integer> values) {
            addCriterion("id_permission in", values, "idPermission");
            return (Criteria) this;
        }

        public Criteria andIdPermissionNotIn(List<Integer> values) {
            addCriterion("id_permission not in", values, "idPermission");
            return (Criteria) this;
        }

        public Criteria andIdPermissionBetween(Integer value1, Integer value2) {
            addCriterion("id_permission between", value1, value2, "idPermission");
            return (Criteria) this;
        }

        public Criteria andIdPermissionNotBetween(Integer value1, Integer value2) {
            addCriterion("id_permission not between", value1, value2, "idPermission");
            return (Criteria) this;
        }

        public Criteria andNamePermissionIsNull() {
            addCriterion("name_permission is null");
            return (Criteria) this;
        }

        public Criteria andNamePermissionIsNotNull() {
            addCriterion("name_permission is not null");
            return (Criteria) this;
        }

        public Criteria andNamePermissionEqualTo(String value) {
            addCriterion("name_permission =", value, "namePermission");
            return (Criteria) this;
        }

        public Criteria andNamePermissionNotEqualTo(String value) {
            addCriterion("name_permission <>", value, "namePermission");
            return (Criteria) this;
        }

        public Criteria andNamePermissionGreaterThan(String value) {
            addCriterion("name_permission >", value, "namePermission");
            return (Criteria) this;
        }

        public Criteria andNamePermissionGreaterThanOrEqualTo(String value) {
            addCriterion("name_permission >=", value, "namePermission");
            return (Criteria) this;
        }

        public Criteria andNamePermissionLessThan(String value) {
            addCriterion("name_permission <", value, "namePermission");
            return (Criteria) this;
        }

        public Criteria andNamePermissionLessThanOrEqualTo(String value) {
            addCriterion("name_permission <=", value, "namePermission");
            return (Criteria) this;
        }

        public Criteria andNamePermissionLike(String value) {
            addCriterion("name_permission like", value, "namePermission");
            return (Criteria) this;
        }

        public Criteria andNamePermissionNotLike(String value) {
            addCriterion("name_permission not like", value, "namePermission");
            return (Criteria) this;
        }

        public Criteria andNamePermissionIn(List<String> values) {
            addCriterion("name_permission in", values, "namePermission");
            return (Criteria) this;
        }

        public Criteria andNamePermissionNotIn(List<String> values) {
            addCriterion("name_permission not in", values, "namePermission");
            return (Criteria) this;
        }

        public Criteria andNamePermissionBetween(String value1, String value2) {
            addCriterion("name_permission between", value1, value2, "namePermission");
            return (Criteria) this;
        }

        public Criteria andNamePermissionNotBetween(String value1, String value2) {
            addCriterion("name_permission not between", value1, value2, "namePermission");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table v_group_permission
     *
     * @mbggenerated do_not_delete_during_merge Tue Oct 08 08:20:18 CEST 2013
     */
public static class Criteria extends GeneratedCriteria implements CriteriaBase{

	 	public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return this;
        }
    	 	public Criteria andIdGroupLike(String value) {
            addCriterion("id_group like", value, "idGroup");
            return this;
        }
    	 	public Criteria andIdPermissionLike(String value) {
            addCriterion("id_permission like", value, "idPermission");
            return this;
        }
    	 	 

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table v_group_permission
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
