package com.prueba.model.vusergroup;

import java.io.Serializable;

import com.prueba.model.EntityBase;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import com.prueba.constraints.XSS;
import com.prueba.gui.importer.ConstraintImportField;
import com.prueba.gui.importer.ConstraintImportTable;

@XmlRootElement
@ConstraintImportTable(keys={})
public class VUserGroup extends EntityBase implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user_group.id
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
	@NotNull
	@ConstraintImportField(columnName="id",messageError="error.vusergroup.id",pattern="^(\\-)?\\d+(\\.\\d+)?$",isPK=false,isCompulsory=false)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user_group.id_user
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
	@NotNull
	@ConstraintImportField(columnName="idUser",messageError="error.vusergroup.idUser",pattern="^(\\-)?\\d+(\\.\\d+)?$",isPK=false,isCompulsory=false)
    private Integer idUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user_group.name_user
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
	@XSS
	@NotNull
	@Size(min=0,max=255)
	@ConstraintImportField(columnName="nameUser",messageError="error.vusergroup.nameUser",pattern=".+",isPK=false,isCompulsory=false)
    private String nameUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user_group.id_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
	@NotNull
	@ConstraintImportField(columnName="idGroup",messageError="error.vusergroup.idGroup",pattern="^(\\-)?\\d+(\\.\\d+)?$",isPK=false,isCompulsory=false)
    private Integer idGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user_group.name_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
	@XSS
	@NotNull
	@Size(min=0,max=45)
	@ConstraintImportField(columnName="nameGroup",messageError="error.vusergroup.nameGroup",pattern=".+",isPK=false,isCompulsory=false)
    private String nameGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user_group.id
     *
     * @return the value of v_user_group.id
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user_group.id
     *
     * @param id the value for v_user_group.id
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user_group.id_user
     *
     * @return the value of v_user_group.id_user
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public Integer getIdUser() {
        return idUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user_group.id_user
     *
     * @param idUser the value for v_user_group.id_user
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user_group.name_user
     *
     * @return the value of v_user_group.name_user
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public String getNameUser() {
        return nameUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user_group.name_user
     *
     * @param nameUser the value for v_user_group.name_user
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public void setNameUser(String nameUser) {
        this.nameUser = nameUser == null ? null : nameUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user_group.id_group
     *
     * @return the value of v_user_group.id_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public Integer getIdGroup() {
        return idGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user_group.id_group
     *
     * @param idGroup the value for v_user_group.id_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public void setIdGroup(Integer idGroup) {
        this.idGroup = idGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user_group.name_group
     *
     * @return the value of v_user_group.name_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public String getNameGroup() {
        return nameGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user_group.name_group
     *
     * @param nameGroup the value for v_user_group.name_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public void setNameGroup(String nameGroup) {
        this.nameGroup = nameGroup == null ? null : nameGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        VUserGroup other = (VUserGroup) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getIdUser() == null ? other.getIdUser() == null : this.getIdUser().equals(other.getIdUser()))
            && (this.getNameUser() == null ? other.getNameUser() == null : this.getNameUser().equals(other.getNameUser()))
            && (this.getIdGroup() == null ? other.getIdGroup() == null : this.getIdGroup().equals(other.getIdGroup()))
            && (this.getNameGroup() == null ? other.getNameGroup() == null : this.getNameGroup().equals(other.getNameGroup()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getIdUser() == null) ? 0 : getIdUser().hashCode());
        result = prime * result + ((getNameUser() == null) ? 0 : getNameUser().hashCode());
        result = prime * result + ((getIdGroup() == null) ? 0 : getIdGroup().hashCode());
        result = prime * result + ((getNameGroup() == null) ? 0 : getNameGroup().hashCode());
        return result;
    }
}
