package com.prueba.persistence.usergroup;

import com.prueba.model.usergroup.UserGroup;
import com.prueba.model.usergroup.UserGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.prueba.persistence.PersistenceBase;
public interface UserGroupMapper extends PersistenceBase<UserGroup, UserGroupExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int countByExample(UserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int deleteByExample(UserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int insert(UserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int insertSelective(UserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    List<UserGroup> selectByExample(UserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    UserGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int updateByExampleSelective(@Param("record") UserGroup record, @Param("example") UserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int updateByExample(@Param("record") UserGroup record, @Param("example") UserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int updateByPrimaryKeySelective(UserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int updateByPrimaryKey(UserGroup record);
}
