package com.prueba.persistence.wshistory;

import com.prueba.model.wshistory.WsHistory;
import com.prueba.model.wshistory.WsHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.prueba.persistence.PersistenceBase;
public interface WsHistoryMapper extends PersistenceBase<WsHistory, WsHistoryExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ws_history
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int countByExample(WsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ws_history
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int deleteByExample(WsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ws_history
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ws_history
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int insert(WsHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ws_history
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int insertSelective(WsHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ws_history
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    List<WsHistory> selectByExample(WsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ws_history
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    WsHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ws_history
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int updateByExampleSelective(@Param("record") WsHistory record, @Param("example") WsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ws_history
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int updateByExample(@Param("record") WsHistory record, @Param("example") WsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ws_history
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int updateByPrimaryKeySelective(WsHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ws_history
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int updateByPrimaryKey(WsHistory record);
}
