package com.prueba.persistence.vusergroup;

import com.prueba.model.vusergroup.VUserGroup;
import com.prueba.model.vusergroup.VUserGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.prueba.persistence.PersistenceBase;
public interface VUserGroupMapper extends PersistenceBase<VUserGroup, VUserGroupExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int countByExample(VUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int deleteByExample(VUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int insert(VUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int insertSelective(VUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    List<VUserGroup> selectByExample(VUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int updateByExampleSelective(@Param("record") VUserGroup record, @Param("example") VUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_group
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int updateByExample(@Param("record") VUserGroup record, @Param("example") VUserGroupExample example);
}
