package com.prueba.persistence.vgrouppermission;

import com.prueba.model.vgrouppermission.VGroupPermission;
import com.prueba.model.vgrouppermission.VGroupPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.prueba.persistence.PersistenceBase;
public interface VGroupPermissionMapper extends PersistenceBase<VGroupPermission, VGroupPermissionExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_group_permission
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int countByExample(VGroupPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_group_permission
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int deleteByExample(VGroupPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_group_permission
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int insert(VGroupPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_group_permission
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int insertSelective(VGroupPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_group_permission
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    List<VGroupPermission> selectByExample(VGroupPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_group_permission
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int updateByExampleSelective(@Param("record") VGroupPermission record, @Param("example") VGroupPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_group_permission
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int updateByExample(@Param("record") VGroupPermission record, @Param("example") VGroupPermissionExample example);
}
