package com.prueba.model.user;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.prueba.model.ExampleBase;
import com.prueba.model.CriteriaBase;
public class UserExample extends ExampleBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andSurname1IsNull() {
            addCriterion("surname1 is null");
            return (Criteria) this;
        }

        public Criteria andSurname1IsNotNull() {
            addCriterion("surname1 is not null");
            return (Criteria) this;
        }

        public Criteria andSurname1EqualTo(String value) {
            addCriterion("surname1 =", value, "surname1");
            return (Criteria) this;
        }

        public Criteria andSurname1NotEqualTo(String value) {
            addCriterion("surname1 <>", value, "surname1");
            return (Criteria) this;
        }

        public Criteria andSurname1GreaterThan(String value) {
            addCriterion("surname1 >", value, "surname1");
            return (Criteria) this;
        }

        public Criteria andSurname1GreaterThanOrEqualTo(String value) {
            addCriterion("surname1 >=", value, "surname1");
            return (Criteria) this;
        }

        public Criteria andSurname1LessThan(String value) {
            addCriterion("surname1 <", value, "surname1");
            return (Criteria) this;
        }

        public Criteria andSurname1LessThanOrEqualTo(String value) {
            addCriterion("surname1 <=", value, "surname1");
            return (Criteria) this;
        }

        public Criteria andSurname1Like(String value) {
            addCriterion("surname1 like", value, "surname1");
            return (Criteria) this;
        }

        public Criteria andSurname1NotLike(String value) {
            addCriterion("surname1 not like", value, "surname1");
            return (Criteria) this;
        }

        public Criteria andSurname1In(List<String> values) {
            addCriterion("surname1 in", values, "surname1");
            return (Criteria) this;
        }

        public Criteria andSurname1NotIn(List<String> values) {
            addCriterion("surname1 not in", values, "surname1");
            return (Criteria) this;
        }

        public Criteria andSurname1Between(String value1, String value2) {
            addCriterion("surname1 between", value1, value2, "surname1");
            return (Criteria) this;
        }

        public Criteria andSurname1NotBetween(String value1, String value2) {
            addCriterion("surname1 not between", value1, value2, "surname1");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andTelephoneIsNull() {
            addCriterion("telephone is null");
            return (Criteria) this;
        }

        public Criteria andTelephoneIsNotNull() {
            addCriterion("telephone is not null");
            return (Criteria) this;
        }

        public Criteria andTelephoneEqualTo(Integer value) {
            addCriterion("telephone =", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneNotEqualTo(Integer value) {
            addCriterion("telephone <>", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneGreaterThan(Integer value) {
            addCriterion("telephone >", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneGreaterThanOrEqualTo(Integer value) {
            addCriterion("telephone >=", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneLessThan(Integer value) {
            addCriterion("telephone <", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneLessThanOrEqualTo(Integer value) {
            addCriterion("telephone <=", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneIn(List<Integer> values) {
            addCriterion("telephone in", values, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneNotIn(List<Integer> values) {
            addCriterion("telephone not in", values, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneBetween(Integer value1, Integer value2) {
            addCriterion("telephone between", value1, value2, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneNotBetween(Integer value1, Integer value2) {
            addCriterion("telephone not between", value1, value2, "telephone");
            return (Criteria) this;
        }

        public Criteria andEnableIsNull() {
            addCriterion("enable is null");
            return (Criteria) this;
        }

        public Criteria andEnableIsNotNull() {
            addCriterion("enable is not null");
            return (Criteria) this;
        }

        public Criteria andEnableEqualTo(Integer value) {
            addCriterion("enable =", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotEqualTo(Integer value) {
            addCriterion("enable <>", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableGreaterThan(Integer value) {
            addCriterion("enable >", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableGreaterThanOrEqualTo(Integer value) {
            addCriterion("enable >=", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableLessThan(Integer value) {
            addCriterion("enable <", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableLessThanOrEqualTo(Integer value) {
            addCriterion("enable <=", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableIn(List<Integer> values) {
            addCriterion("enable in", values, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotIn(List<Integer> values) {
            addCriterion("enable not in", values, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableBetween(Integer value1, Integer value2) {
            addCriterion("enable between", value1, value2, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotBetween(Integer value1, Integer value2) {
            addCriterion("enable not between", value1, value2, "enable");
            return (Criteria) this;
        }

        public Criteria andBlockedIsNull() {
            addCriterion("blocked is null");
            return (Criteria) this;
        }

        public Criteria andBlockedIsNotNull() {
            addCriterion("blocked is not null");
            return (Criteria) this;
        }

        public Criteria andBlockedEqualTo(Integer value) {
            addCriterion("blocked =", value, "blocked");
            return (Criteria) this;
        }

        public Criteria andBlockedNotEqualTo(Integer value) {
            addCriterion("blocked <>", value, "blocked");
            return (Criteria) this;
        }

        public Criteria andBlockedGreaterThan(Integer value) {
            addCriterion("blocked >", value, "blocked");
            return (Criteria) this;
        }

        public Criteria andBlockedGreaterThanOrEqualTo(Integer value) {
            addCriterion("blocked >=", value, "blocked");
            return (Criteria) this;
        }

        public Criteria andBlockedLessThan(Integer value) {
            addCriterion("blocked <", value, "blocked");
            return (Criteria) this;
        }

        public Criteria andBlockedLessThanOrEqualTo(Integer value) {
            addCriterion("blocked <=", value, "blocked");
            return (Criteria) this;
        }

        public Criteria andBlockedIn(List<Integer> values) {
            addCriterion("blocked in", values, "blocked");
            return (Criteria) this;
        }

        public Criteria andBlockedNotIn(List<Integer> values) {
            addCriterion("blocked not in", values, "blocked");
            return (Criteria) this;
        }

        public Criteria andBlockedBetween(Integer value1, Integer value2) {
            addCriterion("blocked between", value1, value2, "blocked");
            return (Criteria) this;
        }

        public Criteria andBlockedNotBetween(Integer value1, Integer value2) {
            addCriterion("blocked not between", value1, value2, "blocked");
            return (Criteria) this;
        }

        public Criteria andAttemptsLoginIsNull() {
            addCriterion("attempts_login is null");
            return (Criteria) this;
        }

        public Criteria andAttemptsLoginIsNotNull() {
            addCriterion("attempts_login is not null");
            return (Criteria) this;
        }

        public Criteria andAttemptsLoginEqualTo(Integer value) {
            addCriterion("attempts_login =", value, "attemptsLogin");
            return (Criteria) this;
        }

        public Criteria andAttemptsLoginNotEqualTo(Integer value) {
            addCriterion("attempts_login <>", value, "attemptsLogin");
            return (Criteria) this;
        }

        public Criteria andAttemptsLoginGreaterThan(Integer value) {
            addCriterion("attempts_login >", value, "attemptsLogin");
            return (Criteria) this;
        }

        public Criteria andAttemptsLoginGreaterThanOrEqualTo(Integer value) {
            addCriterion("attempts_login >=", value, "attemptsLogin");
            return (Criteria) this;
        }

        public Criteria andAttemptsLoginLessThan(Integer value) {
            addCriterion("attempts_login <", value, "attemptsLogin");
            return (Criteria) this;
        }

        public Criteria andAttemptsLoginLessThanOrEqualTo(Integer value) {
            addCriterion("attempts_login <=", value, "attemptsLogin");
            return (Criteria) this;
        }

        public Criteria andAttemptsLoginIn(List<Integer> values) {
            addCriterion("attempts_login in", values, "attemptsLogin");
            return (Criteria) this;
        }

        public Criteria andAttemptsLoginNotIn(List<Integer> values) {
            addCriterion("attempts_login not in", values, "attemptsLogin");
            return (Criteria) this;
        }

        public Criteria andAttemptsLoginBetween(Integer value1, Integer value2) {
            addCriterion("attempts_login between", value1, value2, "attemptsLogin");
            return (Criteria) this;
        }

        public Criteria andAttemptsLoginNotBetween(Integer value1, Integer value2) {
            addCriterion("attempts_login not between", value1, value2, "attemptsLogin");
            return (Criteria) this;
        }

        public Criteria andSurname2IsNull() {
            addCriterion("surname2 is null");
            return (Criteria) this;
        }

        public Criteria andSurname2IsNotNull() {
            addCriterion("surname2 is not null");
            return (Criteria) this;
        }

        public Criteria andSurname2EqualTo(String value) {
            addCriterion("surname2 =", value, "surname2");
            return (Criteria) this;
        }

        public Criteria andSurname2NotEqualTo(String value) {
            addCriterion("surname2 <>", value, "surname2");
            return (Criteria) this;
        }

        public Criteria andSurname2GreaterThan(String value) {
            addCriterion("surname2 >", value, "surname2");
            return (Criteria) this;
        }

        public Criteria andSurname2GreaterThanOrEqualTo(String value) {
            addCriterion("surname2 >=", value, "surname2");
            return (Criteria) this;
        }

        public Criteria andSurname2LessThan(String value) {
            addCriterion("surname2 <", value, "surname2");
            return (Criteria) this;
        }

        public Criteria andSurname2LessThanOrEqualTo(String value) {
            addCriterion("surname2 <=", value, "surname2");
            return (Criteria) this;
        }

        public Criteria andSurname2Like(String value) {
            addCriterion("surname2 like", value, "surname2");
            return (Criteria) this;
        }

        public Criteria andSurname2NotLike(String value) {
            addCriterion("surname2 not like", value, "surname2");
            return (Criteria) this;
        }

        public Criteria andSurname2In(List<String> values) {
            addCriterion("surname2 in", values, "surname2");
            return (Criteria) this;
        }

        public Criteria andSurname2NotIn(List<String> values) {
            addCriterion("surname2 not in", values, "surname2");
            return (Criteria) this;
        }

        public Criteria andSurname2Between(String value1, String value2) {
            addCriterion("surname2 between", value1, value2, "surname2");
            return (Criteria) this;
        }

        public Criteria andSurname2NotBetween(String value1, String value2) {
            addCriterion("surname2 not between", value1, value2, "surname2");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPictureIsNull() {
            addCriterion("picture is null");
            return (Criteria) this;
        }

        public Criteria andPictureIsNotNull() {
            addCriterion("picture is not null");
            return (Criteria) this;
        }

        public Criteria andPictureEqualTo(String value) {
            addCriterion("picture =", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotEqualTo(String value) {
            addCriterion("picture <>", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureGreaterThan(String value) {
            addCriterion("picture >", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureGreaterThanOrEqualTo(String value) {
            addCriterion("picture >=", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureLessThan(String value) {
            addCriterion("picture <", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureLessThanOrEqualTo(String value) {
            addCriterion("picture <=", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureLike(String value) {
            addCriterion("picture like", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotLike(String value) {
            addCriterion("picture not like", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureIn(List<String> values) {
            addCriterion("picture in", values, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotIn(List<String> values) {
            addCriterion("picture not in", values, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureBetween(String value1, String value2) {
            addCriterion("picture between", value1, value2, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotBetween(String value1, String value2) {
            addCriterion("picture not between", value1, value2, "picture");
            return (Criteria) this;
        }

        public Criteria andDateLastPasswordIsNull() {
            addCriterion("date_last_password is null");
            return (Criteria) this;
        }

        public Criteria andDateLastPasswordIsNotNull() {
            addCriterion("date_last_password is not null");
            return (Criteria) this;
        }

        public Criteria andDateLastPasswordEqualTo(Date value) {
            addCriterion("date_last_password =", value, "dateLastPassword");
            return (Criteria) this;
        }

        public Criteria andDateLastPasswordNotEqualTo(Date value) {
            addCriterion("date_last_password <>", value, "dateLastPassword");
            return (Criteria) this;
        }

        public Criteria andDateLastPasswordGreaterThan(Date value) {
            addCriterion("date_last_password >", value, "dateLastPassword");
            return (Criteria) this;
        }

        public Criteria andDateLastPasswordGreaterThanOrEqualTo(Date value) {
            addCriterion("date_last_password >=", value, "dateLastPassword");
            return (Criteria) this;
        }

        public Criteria andDateLastPasswordLessThan(Date value) {
            addCriterion("date_last_password <", value, "dateLastPassword");
            return (Criteria) this;
        }

        public Criteria andDateLastPasswordLessThanOrEqualTo(Date value) {
            addCriterion("date_last_password <=", value, "dateLastPassword");
            return (Criteria) this;
        }

        public Criteria andDateLastPasswordIn(List<Date> values) {
            addCriterion("date_last_password in", values, "dateLastPassword");
            return (Criteria) this;
        }

        public Criteria andDateLastPasswordNotIn(List<Date> values) {
            addCriterion("date_last_password not in", values, "dateLastPassword");
            return (Criteria) this;
        }

        public Criteria andDateLastPasswordBetween(Date value1, Date value2) {
            addCriterion("date_last_password between", value1, value2, "dateLastPassword");
            return (Criteria) this;
        }

        public Criteria andDateLastPasswordNotBetween(Date value1, Date value2) {
            addCriterion("date_last_password not between", value1, value2, "dateLastPassword");
            return (Criteria) this;
        }

        public Criteria andDateLastLoginIsNull() {
            addCriterion("date_last_login is null");
            return (Criteria) this;
        }

        public Criteria andDateLastLoginIsNotNull() {
            addCriterion("date_last_login is not null");
            return (Criteria) this;
        }

        public Criteria andDateLastLoginEqualTo(Date value) {
            addCriterion("date_last_login =", value, "dateLastLogin");
            return (Criteria) this;
        }

        public Criteria andDateLastLoginNotEqualTo(Date value) {
            addCriterion("date_last_login <>", value, "dateLastLogin");
            return (Criteria) this;
        }

        public Criteria andDateLastLoginGreaterThan(Date value) {
            addCriterion("date_last_login >", value, "dateLastLogin");
            return (Criteria) this;
        }

        public Criteria andDateLastLoginGreaterThanOrEqualTo(Date value) {
            addCriterion("date_last_login >=", value, "dateLastLogin");
            return (Criteria) this;
        }

        public Criteria andDateLastLoginLessThan(Date value) {
            addCriterion("date_last_login <", value, "dateLastLogin");
            return (Criteria) this;
        }

        public Criteria andDateLastLoginLessThanOrEqualTo(Date value) {
            addCriterion("date_last_login <=", value, "dateLastLogin");
            return (Criteria) this;
        }

        public Criteria andDateLastLoginIn(List<Date> values) {
            addCriterion("date_last_login in", values, "dateLastLogin");
            return (Criteria) this;
        }

        public Criteria andDateLastLoginNotIn(List<Date> values) {
            addCriterion("date_last_login not in", values, "dateLastLogin");
            return (Criteria) this;
        }

        public Criteria andDateLastLoginBetween(Date value1, Date value2) {
            addCriterion("date_last_login between", value1, value2, "dateLastLogin");
            return (Criteria) this;
        }

        public Criteria andDateLastLoginNotBetween(Date value1, Date value2) {
            addCriterion("date_last_login not between", value1, value2, "dateLastLogin");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user
     *
     * @mbggenerated do_not_delete_during_merge Tue Oct 08 08:20:18 CEST 2013
     */
public static class Criteria extends GeneratedCriteria implements CriteriaBase{

	 	public Criteria andAttemptsLoginLike(String value) {
            addCriterion("attempts_login like", value, "attemptsLogin");
            return this;
        }
    	 	public Criteria andBlockedLike(String value) {
            addCriterion("blocked like", value, "blocked");
            return this;
        }
    	 	public Criteria andDateLastLoginLike(String value) {
            addCriterion("date_last_login like", value, "dateLastLogin");
            return this;
        }
    	 	public Criteria andDateLastPasswordLike(String value) {
            addCriterion("date_last_password like", value, "dateLastPassword");
            return this;
        }
    	 	 	public Criteria andEnableLike(String value) {
            addCriterion("enable like", value, "enable");
            return this;
        }
    	 	public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return this;
        }
    	 	 	 	 	 	 	public Criteria andTelephoneLike(String value) {
            addCriterion("telephone like", value, "telephone");
            return this;
        }
    	 

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
