package com.prueba.model.prueba;

import java.io.Serializable;
import java.util.Date;

import com.prueba.model.EntityBase;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import com.prueba.constraints.XSS;
import com.prueba.gui.importer.ConstraintImportField;
import com.prueba.gui.importer.ConstraintImportTable;

@XmlRootElement
@ConstraintImportTable(keys={"id"})
public class Prueba extends EntityBase implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_prueba.id
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
	@NotNull
	@ConstraintImportField(columnName="id",messageError="error.prueba.id",pattern="^(\\-)?\\d+(\\.\\d+)?$",isPK=true,isCompulsory=true)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_prueba.nombre
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
	@XSS
	@NotNull
	@Size(min=0,max=2500)
	@ConstraintImportField(columnName="nombre",messageError="error.prueba.nombre",pattern=".+",isPK=false,isCompulsory=false)
    private String nombre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_prueba.numero
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
	@NotNull
	@ConstraintImportField(columnName="numero",messageError="error.prueba.numero",pattern="^(\\-)?\\d+(\\.\\d+)?$",isPK=false,isCompulsory=false)
    private Integer numero;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_prueba.fecha
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
	@NotNull
	@ConstraintImportField(columnName="fecha",messageError="error.prueba.fecha",pattern="^^(0[1-9]|[12][0-9]|3[01])[- /.](0[1-9]|1[012])[- /.](19|20)\\d\\d$",isPK=false,isCompulsory=false)
    private Date fecha;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_prueba
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_prueba.id
     *
     * @return the value of t_prueba.id
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_prueba.id
     *
     * @param id the value for t_prueba.id
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_prueba.nombre
     *
     * @return the value of t_prueba.nombre
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_prueba.nombre
     *
     * @param nombre the value for t_prueba.nombre
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public void setNombre(String nombre) {
        this.nombre = nombre == null ? null : nombre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_prueba.numero
     *
     * @return the value of t_prueba.numero
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public Integer getNumero() {
        return numero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_prueba.numero
     *
     * @param numero the value for t_prueba.numero
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public void setNumero(Integer numero) {
        this.numero = numero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_prueba.fecha
     *
     * @return the value of t_prueba.fecha
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public Date getFecha() {
        return fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_prueba.fecha
     *
     * @param fecha the value for t_prueba.fecha
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prueba
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Prueba other = (Prueba) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getNombre() == null ? other.getNombre() == null : this.getNombre().equals(other.getNombre()))
            && (this.getNumero() == null ? other.getNumero() == null : this.getNumero().equals(other.getNumero()))
            && (this.getFecha() == null ? other.getFecha() == null : this.getFecha().equals(other.getFecha()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prueba
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getNombre() == null) ? 0 : getNombre().hashCode());
        result = prime * result + ((getNumero() == null) ? 0 : getNumero().hashCode());
        result = prime * result + ((getFecha() == null) ? 0 : getFecha().hashCode());
        return result;
    }
}
