package com.prueba.persistence.prueba;

import com.prueba.model.prueba.Prueba;
import com.prueba.model.prueba.PruebaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.prueba.persistence.PersistenceBase;
public interface PruebaMapper extends PersistenceBase<Prueba, PruebaExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prueba
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int countByExample(PruebaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prueba
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int deleteByExample(PruebaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prueba
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prueba
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int insert(Prueba record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prueba
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int insertSelective(Prueba record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prueba
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    List<Prueba> selectByExample(PruebaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prueba
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    Prueba selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prueba
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int updateByExampleSelective(@Param("record") Prueba record, @Param("example") PruebaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prueba
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int updateByExample(@Param("record") Prueba record, @Param("example") PruebaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prueba
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int updateByPrimaryKeySelective(Prueba record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prueba
     *
     * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
     */
    int updateByPrimaryKey(Prueba record);
}
